### ISSUE TITLE
Prototype : 入力を実装する

### ISSUE THREAD

**Issue by matsumoto36** [matsumoto36/RogueLikeShooting#1]
wikiにあるクラス図を参考に、プレイヤーが入力を知れる仕組みを作る。
プロトタイプなので、キーボード入力のみでもOK

コントローラーとキーボードの違いを、プレイヤーが意識しなくてもいいように作るとよき

入力一覧
移動 : WASDキー
向き変更 : マウス位置
攻撃 : 左クリック

**Comment by HaruRabbi** [comment]
実装内容
移動：WASD(↑↓→←)キー
方向：マウス位置
攻撃：左クリック
完了しました
